import "./css/example.css";
import { AppClass } from "./AppClass";
import { Hello } from "./components/Hello";
import { HelloInDeutsch} from "./components/HelloInDeutsch"; 


// creating application: npx cearte-react-app [name_of_the_app]
// for starting, navigate to newly created folder with command: cd name_of_the_app
// then execute an app with the command: npm start

// how to start application which is not generated by me
// navigate to the app folder, execute command npm install
// and then execute with command npm start

// This is functional component
function App() {
  let number = 10;

  const element = <h1>Hello from javascript react</h1>;

  function toUpperCaseName(user){
    return user.name.toUpperCase();
  }

  const student ={
    name:"Martin",
    lastName: "Trajkov",
    image: "https://thispersondoesnotexist.com/"
  };

  function print() {
    console.log("I was clicked");
  }

  // jsx e sintaksna ekstenzija na javascript, no toa ne e nitu javascript,
  // nitu html no ja ima mokjta i funkcionalnostite na dvete
  // RULE: When we want to use javascript in jsx we use {} brackets

  //Da kreirame funkcionalna komponenta kade vo nekoi html elementi
  // kje gi stavite vashita 3 hobia
  // A potoa da kreirame druga komponenta vo koja kje go stavite vashto omileno hobi

  //Da kreirame i treta komponenta kade kje imame nekoj tekst
  // koj kje bide eve slika od moeto omileno hoby
  // da ima slika od hobito
  // da stavime css vnatre da toj tekst e oboen vo nekoja razlichna boja
  // i normalno slikata da ni bide vo razmer i toj css da bide
  // importiran od nekoj nadvoreshen css file
  // koga kje pomineme so mous-ot vrz slikata da ispechatime vo
  // konzola nekoj tekst (hello there!!!)
  return (
    <div className="App">
      {/* <h1 className="react-hello">Hello from Raect!<h1> */}
      {/* <p>5+5</p> 
      <p>{5+5+number} result from this shoul be 20</p>
      {element} */}
      {/*<h1>Hello, {toUpperCaseName("sanja")}</h1>*/}
      <h1>Hello, {toUpperCaseName(student)}</h1>
      <a tagret="blank" href="http://google.com">
        Google
      </a>
      <img src={student.image} style={{ width: 300, height: 300}}></img>
      {/* <button onClick={print}>Click me</button>} */}
      {/* <AppClass /> */}
      <Hello />
      <HelloInDeutsch />
    </div>
  );
}
export default App;
